### ISSUE TITLE
Potential topic: Making nice maps (in R)

### ISSUE THREAD

**Issue by richardsc** [dankelley/AMORE#4]
Projections? Adding stuff? Bathymetry?

**Comment by YukonJan** [comment]
This may be specific to me but could we cover overlaying GPS tracks on a map?

**Comment by dankelley** [comment]
@YukonJan good question to bring up during the meeting tomorrow.  If you have a data file, you might want to bring it along on a USB stick.

**Comment by richardsc** [comment]
Have we decided that this is what we're going to cover tomorrow? 

If so, could you also email the GPS track file to me so I can make sure I know how to read it before starting? 😄

**Comment by dankelley** [comment]
Yup, decided.  @YukonJan please also email me the file because I may have code that can plot it.  (I used to plot my runs and I might still have that code around somewhere.)

**Comment by dankelley** [comment]
Oh, I see, oce can read `.gpx` files (https://dankelley.github.io/oce/reference/read.gps.html)

**Comment by dankelley** [comment]
I'm closing this because the session already took place, and minutes have been posted.
