### ISSUE TITLE
Potential topic: Rmarkdown

### ISSUE THREAD

**Issue by cameronrichrdson** [dankelley/AMORE#6]
As suggested in AMORE-20230614, a possible future AMORE session on using R-markdown as a tool for documentation?

**Comment by MacDonaldJacob** [comment]
All of the suggested topics are of interest to me. I did suggest this one as I am hoping to learn to better write reports and documents in R-markdown/with LaTeX, looking to make the process more efficient or even partially automated as I have previously spent a lot of time formatting to make a nice-looking document.
